phone: +92 305 2584473
site_name: TON1K
whatsapp_note: WhatsApp available 24/7
navbar:
  links:
    - display_text: Portfolio
      url: "#portfolio"
    - display_text: About
      url: "#hero"
    - display_text: FAQ's
      url: "#faqs"
  cta_button:
    display_text: Get Started
    url: "#get-started"
footer:
  contact_email: awtgamezz@gmail.com
  copyright_year: "2026"
  socials:
    upwork: https://www.upwork.com/freelancers/tonikc
    discord: https://discord.gg/f438t3YWA
    whatsapp: https://wa.me/+923052584473
    x_twitter: https://x.com/WaxehToKo
    instagram: https://www.instagram.com/waxeh_baig
